site_name: PyQtGraph-GIS Documentation
site_url: https://olemeif.github.io/pyqtgraph-gis/
repo_url: https://github.com/olemeif/pyqtgraph-gis
repo_name: olemeif/pyqtgraph-gis
edit_uri: edit/main/docs/
site_description: >-
  Documentation for the PyQtGraph-GIS library.
  Setup Guide and Tutorials on how to create Map-Apps with Python and PyQtGraph-GIS.
theme:
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.integrate
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/olemeif/pyqtgraph-gis
      name: PyQtGraph-GIS on GitHub
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

copyright: >
  Copyright &copy; 2026 Ole Meiforth –
  <a href="#__consent">Change cookie settings</a>
plugins:
  - privacy
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details